### ISSUE TITLE
Bundles, another bundle

### ISSUE THREAD

**Issue by theofidry** [lafourchette/FixturesBundle#11]
Just out of curiosity why not using [AliceBundle](https://github.com/hautelook/AliceBundle)?

**Comment by vincentchalamon** [comment]
DoctrineFixturesBundle [does not allow to purge database](https://github.com/doctrine/DoctrineFixturesBundle/issues/50) with truncate because of foreign keys. AliceBundle uses DoctrineFixturesBundle, that's why we decided to code our own FixturesBundle, using correct MySQL truncate before load

**Comment by theofidry** [comment]
AliceBundle 1.0 does not use DoctrineFixturesBundle although it can works with it. That being said I think the issue still remains but does not need much to be solved cf. hautelook/AliceBundle#121, doctrine/data-fixtures#113.

**Comment by vincentchalamon** [comment]
OK, [AliceBundle](https://github.com/hautelook/AliceBundle) just released v1.0.0 on September 30th. We'll see if we have enough time to refacto our code.
/cc @guillaumevoisin @MLKiiwy @oversanne

**Comment by MLKiiwy** [comment]
@theofidry AliceBundle doesn't implemets all our needs, our main feature is the "Group" and "dependency" system (and "set" system), wich is really usefull when you have MANY fixtures. You have also directly the behat implementation in the bundle like (https://github.com/theofidry/AliceBundleExtension) but oriented to use our dependency system.

**Comment by theofidry** [comment]
@MLKiiwy I'm well aware there have to be features lacking!

I've been frustrated a long time with fixtures management because there's so much bundles but the only most famous one was DoctrineFixturesBundle and HautelookAliceBundle. Both were completely inactive. Somehow I manage to get write access on HautelookAliceBundle and upgraded it to nelmio/alice 2.0 and added some features that I could find on other bundles too.

So to sum up HautelookAliceBundle is far more active now and provides more features than before with the 1.0. My point is I would rather like having one good bundle rather than 2, 3 or 4 bundles which all do the same thing except for one or two things. So any work to achieve that is warmly welcomed! 

>You have also directly the behat implementation in the bundle like (https://github.com/theofidry/AliceBundleExtension) but oriented to use our dependency system.

It's a bit different actually. With this extension you tend to do more fixtures on a scenario/feature basis, which really lighten up the fixtures an allow to have more control on it.

**Comment by MLKiiwy** [comment]
@theofidry actually we decided to close this bundle completely and switching to https://github.com/KnpLabs/FriendlyContexts
See our fork to have all the new features we implements : https://github.com/lafourchette/FriendlyContexts and if you want you can help us to improve this bundle ( https://github.com/KnpLabs/FriendlyContexts/pulls many PR to validate )

**Comment by theofidry** [comment]
Ok good to know. But to me there's a huge difference as [KnpLabsFriendlyContexts][1] is exclusively for Behat whereas this bundle or [HautelookAliceBundle][2] are both usable completely outside of Behat :/

[1]: https://github.com/KnpLabs/FriendlyContexts
[2]: https://github.com/hautelook/AliceBundle

**Comment by vincentchalamon** [comment]
@theofidry Yes, I understand. But for our needs in LaFourchette, KnpLabsFriendlyContexts does perfectly what we expect :)
I keep HautelookAliceBundle for some other needs, just in case, thanks for sharing :)
